### ISSUE TITLE
roxctl used in tekton image tasks aren't executable as script

### ISSUE THREAD

**Issue by shin-san** [stackrox/stackrox#5053] opened 2023-03-01 01:09 UTC
### Bug report
The [rhacs-image-scan Tekton Task](https://hub.tekton.dev/tekton/task/rhacs-image-scan)'s image would throw an error when `script` is used as opposed to `args` as per details below.

Since all rhacs-related Tekton Tasks are using the same `roxctl` image, it is fair to say that the following Tekton Tasks are all affected:
1. `rhacs-image-scan`
2. `rhacs-image-check`
3. `rhacs-deployment-check`

```
    - name: rox-image-scan
      script: >-
        #!/usr/bin/env sh

        set -ex

        echo "Initiating image scan..."

        roxctl image scan --endpoint=$(ROX_CENTRAL_ENDPOINT)
        --insecure-skip-tls-verify=$(INSECURE) --output=$(OUTPUT)
        --image=$(IMAGE) >> /tmp/image-scan-report

        cat /tmp/image-scan-report | tee $(results.image-scan-report.path)
```
```
image-scan
STEP-ROX-IMAGE-SCAN

2023/03/01 00:54:25 Error executing command: fork/exec /tekton/scripts/script-0-9wm4x: no such file or directory
```
### Expected behavior
Able to use `script` in a Tekton Task

### Steps to reproduce the problem
Execute the following Task using `roxctl` image:
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: rhacs-image-scan
  annotations:
    description: >-
      Scan an image with Red Hat Advanced Cluster Security.
spec:
  results:
    - name: image-scan-report
      description: Image Scan Report
  steps:
    - name: print-version
      image: "quay.io/stackrox-io/roxctl:3.71.0"
      script: |-
        #!/usr/bin/env sh
        set -ex
        
        echo "Initiating image scan..."
        roxctl version
```

**Comment by ovalenti** [comment] 2023-03-01 14:40
Hello @shin-san, and thanks for this report.

When you run the task, do you get the output of the "echo" commands before it fails ? This is just to check whether the script runs at all.

**Comment by shin-san** [comment] 2023-03-01 16:33
Hi @ovalenti, unfortunately it does not even get to run the `echo` command. It seems that tekton was unable to execute `shell` command from what I have tested.

**Comment by ovalenti** [comment] 2023-03-01 16:49
It would be strange, but could it be that `/usr/bin/env` or the shell does not exist in the image, @shin-san ?

**Comment by shin-san** [comment] 2023-03-01 21:39
I tested `script` without `/usr/bin/env` or `/bin/bash`, and based from the outcome, `script` defaults to using shell to execute the commands you provide it and that itself is an issue if the image does not contain shell as part of its containerisation.

```
  steps:
    - image: quay.io/stackrox-io/roxctl:3.74.0
      name: rox-image-scan
      script: roxtctl version
```

Outcome:
```
STEP-ROX-IMAGE-SCAN

2023/03/01 21:31:48 Error executing command: fork/exec /tekton/scripts/script-0-v9rlc: no such file or directory
```

**Comment by ovalenti** [comment] 2023-03-02 08:50
Hi @shin-san, thanks for the clarification. I believe I understand your request now :sweat_smile: 

I will draw some attention on this.

**Comment by ovalenti** [comment] 2023-03-02 09:04
Might be worth mentioning @dlbewley here as well, since he contributed the task. :wave:

**Comment by dlbewley** [comment] 2023-03-02 16:12
Hi @shin-san this is as intended. The rhacs tasks referenced use the roxctl image from Red Hat and leverage the container's entrypoint of `roxctl` directly. 

If you have a preference for a scripted approach you may find the stackrox tasks to be relevant. They are less integrated in that they do not use the roxctl image, but download the binary on the fly to a larger linux image. eg https://github.com/tektoncd/catalog/tree/main/task/stackrox-image-scan/0.1

**Comment by shin-san** [comment] 2023-03-05 02:13
Hi @dlbewley my concern with the other stackrox tasks is that the base image is running a centos base image and just simply downloading the cli.

My concern is the fact that the supply chain is not secure and would make sense if the provided image is coming from Red Hat directly. This is mainly due to our use-case where images signatures will be validated prior to deployment.

**Comment by porridge** [comment] 2023-05-25 06:33
@shin-san if I understand you correctly, you're asking for a RedHat-supported `roxctl` image that contains a basic OS image apart from the `roxctl` binary itself? If so, may I ask you close this ticket and open an RFE with Red Hat customer support?

**Comment by shin-san** [comment] 2023-10-10 06:19
@porridge , I am not quite sure how to raise an RFE ticket with Red Hat unfortunately. Happy to close this ticket but I believe there is still value in being able to use certain cli commands given the limitation with tekton pipelines in storing results as per this [doco](https://github.com/tektoncd/pipeline/blob/main/docs/tasks.md#emitting-object-results).

**Comment by shin-san** [comment] 2023-10-10 23:05
@porridge it was initially a requirement for client and I do not have access to Red Hat support or at least that I am aware of.

Well, I do not know who owns the image for `quay.io/stackrox-io/roxctl`, so I thought raising it here is appropriate.

Happy to be directed where and who should I raise it to.

**Comment by porridge** [comment] 2023-10-11 04:41
Yes, this is the correct place @shin-san , I only summoned the relevant poeple.

**Comment by janisz** [comment] 2024-04-03 13:24
@shin-san Apologies for the extended period of silence. As previously stated, the current functionality operates as expected. The image is kept minimal. If additional processing is required for the output, it might be necessary to save the output and pass it to the subsequent task, which is designed to handle processing on a larger image.

Currently, our focus is on enhancing the user experience of roxctl usage in CI. If you have any further suggestions, please feel free to raise them as new issues here.

For now, I will proceed to close this particular issue.

**Closed by janisz** 2024-04-03 13:24 UTC

**Comment by rhybrillou** [comment] 2024-04-22 07:33
PR #10703 should help perform actions on the output of the roxctl action.
