### ISSUE TITLE
roxctl generate netpol extra YAML addition

### ISSUE THREAD

**Issue by mfosterrox** [stackrox/stackrox#3404] opened 2022-10-12 17:47 UTC

**Comment by janisz** [comment] 2022-10-13 09:26
@mfosterrox Could you add more context?

**Comment by Maddosaurus** [comment] 2022-10-13 11:55
I suppose this is a duplicate of https://github.com/stackrox/stackrox/issues/3405, correct @mfosterrox?
I'm closing this off, but please feel free to reopen should this be wrong :)

**Closed by Maddosaurus** 2022-10-13 11:55 UTC
