### ISSUE TITLE
Policy image exclusion

### ISSUE THREAD

**Issue by mtcolman** [stackrox/stackrox#2952] opened 2022-09-02 11:06 UTC
When creating a policy in ACS (v3.71.0), is it possible to exclude images by registry or repo?

It would appear (from the "policy scope" page) that I can only do this by selecting (one or many) individual images, which are then referencing specific tags?

![image](https://user-images.githubusercontent.com/33348891/188125279-086d7ade-b4a4-4ad3-981b-a7584aec6764.png)

As shown here, I think I'm limited to the specific image versions in the list:

![image](https://user-images.githubusercontent.com/33348891/188126331-95ce67ce-bf1d-4828-9049-878ae89343b2.png)

When I select the images, it cannot remove tags to make it more generic, i.e., by image repository or at the registry level.

For example, perhaps I want a policy "don't allow root user" to be applied to everything except my image `examplereg.com/rootimage` and I don't want this to be limited to just the current version, because future versions will need the same exemption.

Or, I might want a policy based on a specific CVSS rating threshold to apply to all images in my dev registry `devexample.com/*`, but I want a policy with a different CVSS rating threshold applied to my Pre-Production registry `preprodexample.com/*`.

Have I missed where I can do this, or is this functionality missing from ACS/Stackrox?

**Comment by ivan-degtiarenko** [comment] 2022-09-29 13:30
Hey @mtcolman,

sorry for the late response. It's possible to exclude images based on the **prefix** of their name. To do that, start typing in the `Select images to exclude` field and you'll see `Create <image name>` option at the bottom of the list:
<img width="1483" alt="Screenshot 2022-09-29 at 15 26 33" src="https://user-images.githubusercontent.com/78353299/193044019-d42a184c-d4a1-4ef2-8e7f-304f2a0ae43f.png">

That should allow for both use cases(all versions of a certain image and all images in a certain registry) to work.

Is that helpful?

**Comment by mtcolman** [comment] 2022-09-29 13:59
@ivan-degtiarenko that's very helpful, thank you. Might it be worth making it clearer in the GUI that this can be done? And is it documented anywhere that I've missed? Otherwise could documentation be created/updated to make this clear?

Thanks!

**Comment by Maddosaurus** [comment] 2023-02-02 08:14
Hey folks!
As some time has passed and the change has been incorporated in the release, I am closing this issue as done.
@mtcolman feel free to reopen or comment, if you have further questions or think the issue is not resolved!

**Closed by Maddosaurus** 2023-02-02 08:14 UTC
